//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfWebShopLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class order1
    {
        public int Id { get; set; }
        public int aantal { get; set; }
        public string product_naam { get; set; }
        public string gebruiker_naam { get; set; }
    
        public virtual gebruiker1 gebruiker { get; set; }
        public virtual product1 product { get; set; }
    }
}
